---
title: Exploratory Data Analysis, Week of 11/28/2022
author: Daniel Sussman
date: '2022-11-29'
slug: []
categories: []
tags: []
description: ~
toc: yes
authors: []
series: []
lastmod: '2022-11-29T22:19:58-05:00'
featuredVideo: ~
featuredImage: ~
---

For the final two blog posts I’m looking to see how you plan to wrap up the project. I’d like to hear about three things.
How are you continuing your exploratory data analysis? Remember all the ways we visualized the COVID data in just a couple days. Make sure you’ve done a thorough exploration for your project. Lots of ideas will be dead ends but keep looking and think about attaching more data.
What is your tentative thesis? Note that a thesis is not a hypothesis or a question. It should in some ways answer a question. (Eg. rather than, “What are the patterns of housing prices in Boston?“, something like, “Housing prices in Boston are rising rapidly, especially near T stations and along the water.“) The rest of the project should work to support that thesis. That doesn’t mean there won’t be any caveats or uncertainty, but you should try to accurately  provide details that provide evidence for your thesis.
How do you plan to polish your visualizations and tables? Think about titles, captions, annotations, highlights. Look into ggpubr for tools to improve your figures and look into some of the options for displaying tables using https://gallery.htmlwidgets.org/.
Please answer these questions over the next two weeks in your posts, in whatever order you like.


```{r hannah_notes}
suppressPackageStartupMessages(library(tidyverse))
load(here::here("dataset", "baseball.RData"))
baseball_2<-baseball %>% group_by(year,h_name) %>% summarize(win=mean(score_diff))

load(here::here("dataset","mlb_payroll.Rdata"))

load(here::here("dataset","win_perc.Rdata"))

combined<-full_join(mlb_payroll,win_perc,by=c('year','h_name'))

ggplot(combined)+geom_point(aes(payroll,win_perc))+facet_wrap(vars(h_name))
```