---
title: Potential Data Sets, Week of 10/10/2022
author: Daniel Sussman
date: '2022-10-11'
slug: []
categories: []
tags: []
description: ~
toc: yes
authors: []
series: []
lastmod: '2022-10-11T09:13:35-04:00'
featuredVideo: ~
featuredImage: ~
---

## Data Set 1
Link to data set: https://data.world/dataquest/mlb-game-logs/workspace/file?filename=game_logs.csv
<br/>
<br/>
This data set provides statistics for every MLB game played from 1871 up until the 2016 season.  The data was collected and organized by baseball historians for the public to access and explore. There are 171,907 rows and 161 columns providing information including, the date and day of the week the game was played, the location of the game played, as well as the hits, runs, strikeouts, and walks for the visiting and home team. 127 separate CSV files representing different seasons were combined into this one data set. 
<br/>
<br/>
With this data set, we hope to address the question, "What factors have an influence on an MLB team winning or losing?" Within this larger question, we would be able to explore other patterns like between starting pitchers against a specific team. The data set appears to be missing games from the 1970s and 1990s. This is relatively recent data that is missing which will have an affect on the analyses. Additionally, there are a lot of missing statistics for games played in the 1800s. To avoid these problems, it's possible to filter the data set to only provide seasons 2000-2016 which are recent and include all statistics. Furthermore, this data set could later be combined with a weather data set to explore how certain weather factors, like wind speed, affect the outcome of a game.


## Data Set 2
Link to data set:
https://data.cms.gov/provider-summary-by-type-of-service/medicare-part-d-prescribers/medicare-part-d-prescribers-by-geography-and-drug/data

This data set provides information for each year 2013-2020 on prescription drugs, their prescription patterns, cost, beneficiaries, and more at both the federal and state level. There are 115,410 rows, and 22 columns. It was collected from CMS administrative claims data for medicare beneficiaries, available from the CMS chronic condition data warehouse.  One of the most immediate challenges would certainly be understanding some of the column titles like 'LIS_Bene_Cst_Shr'. As well, if we wanted to correlate these prescription patterns with broader trends, it would be difficult to decide what sort of social factors may be impacting; even then, correlation != causation.


## Data Set 3

Link to data set: https://catalog.data.gov/dataset/dhs-data-dashboard 

This is a data set describing the reported sheltered homeless individuals in NYC over a period of seven years at intervals of several months. It provides data about demographics and is collected by a federal agency. 

This data set has 58 columns, 91 rows, and was collected by the Department of Homeless Services. We were able to load the data and it doesn't appear to require very much if any cleaning. We had hoped to answer the question of homeless trends with respect to housing prices. The problem we have encountered is finding housing data for NYC that matches the time span that the homeless data was collected. We want to show trends over a long period of time, but many of the housing data sets we found were collected over a much shorter period of time. There's also an inconsistency in size, the housing data sets being much larger with much more data than the homeless data sets. We believe that this might prove very difficult if we were to pursue this project. 
