---
title: Data Loading and Cleaning, Week of 10/17/2022
author: Daniel Sussman
date: '2022-10-19'
slug: []
categories: []
tags: []
description: ~
toc: yes
authors: []
series: []
lastmod: '2022-10-19T09:38:50-04:00'
featuredVideo: ~
featuredImage: ~
---

Our data set of MLB game statistics is >50mb and can be found in the dataset-ignore folder. After reading in the CSV file, we converted it into a tibble. 

\n
\n

This data set does not specify whether the home team wins or loses, but it does contain information on the home team's and the away team's number of runs. Since we are interested in seeing if a team wins or loses, we created a column in the dataset called score_diff, which takes the number of the visiting team's runs subtracted from the number of the one team's runs. A positive value represents a win, a negative value represents a loss, and a zero is a tie. The higher absolute values represent a bigger win/loss.

baseball %>% group_by(h_name) %>% mutate(score_diff=h_score-v_score)

Here, we grouped by home team since we will be considering wins and losses for specific teams at their respective stadiums.

\n
\n

The date in the data is inserted as an integer, so using separate, we separated the date into three columns: year, month, and day. If we need to combine these, we can easily do so later on using lubridate.

baseball %>% separate(date,into=c("year","month_day"),sep=4) %>% 
             separate(month_day,into=c("month","day"),sep=2)
             
\n
\n

Some filters we are considering are to filter by home team, and to filter for the years between 2000 and 2016.

baseball %>% filter(h_name="BOS")

We filtered to select Boston Red Sox as the home team, since we have already found weather data for Boston and are considering taking this into account later on.

years<-c(2000,2001,2002,20032004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016)))
baseball%>%filter(year==years)


plots
mean scores?
day of week?
visiting team?


INSTRUCTIONS:


Discuss any initial steps you are taking to load and clean the data.
If you are working with a large data set, you might decide to start with a subset of the data. How did you choose this?
Are you starting by removing missing values or focusing on columns with less missing data.
Exploratory Data Analysis
Talk about your initial exploration of the data.
Give summary statistics and make plots about parts of the data that will be your focus. You might focus on just a few variables.
What are the big, obvious patterns in the data? Are these surprising?
