---
title: Blog Post 4, Week of 10/31/2022
author: Daniel Sussman
date: '2022-11-03'
slug: []
categories: []
tags: []
description: ~
toc: yes
authors: []
series: []
lastmod: '2022-11-03T19:02:24-04:00'
featuredVideo: ~
featuredImage: ~
---

Two graphs EDA, one modeling graph

Graph #1 - Truly Exploratory Data: 
Potential Exploration: 
 - Day vs Night games?
 - If winning momntum or losing momentum exists, ei. does a previously lost game make u more     likely to lose?


Graph #2 - An experiment in the accuracy of the Pythagorean Winning Percentage (PWP)

$$Pythagroean\ Winning\ Percentage = runs\ scored\ ^{2} / (run\ scored\ ^{2} + runs\ allowed\  ^{2})$$
Compare the PWP to the actual winning percentage of the team. 
 - create winning percentage column: mutate(if(h_score>v_score) add column = win or TRUE )
      do a similar mutation for losses, and sum the wins divided by total 
 - Pythagorean column: baseball %>% mutate(pwp = h_score^2 / (h_score^2 + v_score^2))  
 - group by team and filter for only one team
 - plot one teams pwd vs year, and the actual winning percentage per year or season 

 missing a group my season or group  by year (however baseball works) in here somewhere 
 
```{r}
library(tidyverse)
data <- read_csv(here::here("dataset-ignore", "game_logs.csv"))
baseball <- as_tibble(data)
years<-c(2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016)
#cleaned dataset to work with
(baseball <- baseball %>% separate(date,into=c("year","month_day"),sep=4) %>% 
  separate(month_day,into=c("month","day"),sep=2) %>% 
  filter(year %in% years) %>% 
  mutate(score_diff=h_score-v_score))

#win/loss column (1 = win, 0 = loss or tie)
h_win_loss <- function(h, v) {
  ifelse(h > v, 1, 0)
}
(baseball <- baseball %>% mutate(h_win_loss = h_win_loss(h_score, v_score)))

#red sox games
bos <- baseball %>% filter(h_name == "BOS"|v_name == "BOS")

#for all teams
#total games won
home_wins <- baseball %>% group_by(h_name, year) %>% summarize(h_wins = sum(h_win_loss == 1))
away_wins <- baseball %>% group_by(v_name, year) %>% summarize(a_wins = sum(h_win_loss == 0)) %>% rename(h_name = v_name)
team_year_wins <- home_wins %>% add_column(a_wins = away_wins$a_wins) %>% mutate(games_won = h_wins + a_wins)
#total games played
home_games <- baseball %>% group_by(h_name, year) %>% summarize(home_games = n())
away_games <- baseball %>% group_by(v_name, year) %>% summarize(away_games = n()) %>% rename(h_name = v_name)
games_played <- home_games %>% add_column(away_games = away_games$away_games) %>% mutate(game_played = home_games + away_games)

#for Boston Red Sox, grouped by season/year, actual winning percentage
h_wins <- bos %>% filter(h_name == "BOS") %>% group_by(year) %>% summarize(home_games_won = sum(h_win_loss == 1))
a_wins <- bos %>% filter(v_name == "BOS") %>% group_by(year) %>% summarize(away_games_won = sum(h_win_loss == 0))
wins <- h_wins %>% left_join(a_wins, by = "year") %>% mutate(games_won = home_games_won + away_games_won)

(win_percentage <- baseball %>% filter(h_name == "BOS" | v_name == "BOS") %>% 
  group_by(year) %>% 
  summarize(total_games_played = n()) %>% 
  left_join(wins, by = "year") %>% 
  mutate(win_percentage = games_won/total_games_played))
  
#for Boston Red Sox, grouped by season/year, Pythagorean winning percentage
runs_home <- bos %>% filter(h_name == "BOS") %>% group_by(year) %>% summarize(runs_at_home = sum(h_score))
runs_away <- bos %>% filter(v_name == "BOS") %>% group_by(year) %>% summarize(runs_away = sum(v_score))
total_runs <- runs_home %>% left_join(runs_away, by = "year") %>% mutate(total_runs = runs_at_home + runs_away)

home_allowed <- bos %>% filter(h_name == "BOS") %>% group_by(year) %>% summarize(home_allowed = sum(v_score))
away_allowed <- bos %>% filter(v_name == "BOS") %>% group_by(year) %>% summarize(away_allowed = sum(h_score))
total_allowed <- home_allowed %>% left_join(away_allowed, by = "year") %>% mutate(total_allowed = home_allowed + away_allowed)

pythag <- total_runs %>% left_join(total_allowed, by = "year") %>% mutate(pythag_win = ((total_runs)^2)/(((total_runs)^2) + ((total_allowed)^2))) %>% left_join(win_percentage, by = "year")

#barplot
pythag %>% select(year, win_percentage, pythag_win) %>% pivot_longer(-year, names_to = "win_pythag", values_to = "percentage") %>% ggplot(aes(x=year, y=percentage, fill = win_pythag)) + geom_bar(stat = "identity", position = "dodge") + scale_x_discrete(guide = guide_axis(n.dodge=2))
```

Graph #3 - A logistical model predicting wins or losses

In Blogposts 2/3, you should have identified some of the big obvious trends in the data. One question to ask now is whether those trends are the interesting or boring part of the data. In other words, do you want to get a more detailed explanation for the trend by exploring its relationship to other variables? Or do you want to explore some other relationship that might be confounded by the major trend you identified? Overall, both of these require you to start to explore further in your data. Think about exploring both for breadth (looking at relationships among many different variables or groupings) and depth (developing a better understanding of a specific relationship and how other variables fit in).
Additionally, now is a good time to start thinking about statistical modeling. What response variable are you interested in? What predictor variables? Are there transformations of columns that you’d need to do to create interesting predictors? What type of model do you want to fit? Linear? Logistic? Or something else? (Ask me!)
For this week’s blog post, discuss both going deeper and broader into your EDA and your initial thoughts and results for modeling. As always, make lots of plots and try different types of plots. However, for this week’s post, only include at most 2 figures/tables/output for your EDA and at most 1 figure/table/output for the modeling. Try to put together figures that illustrate the main lesson’s you’ve learned this week.
