---
title: Data Equity, Week of 10/24/2022
author: Daniel Sussman
date: '2022-10-24'
slug: []
categories: []
tags: []
description: ~
toc: yes
authors: []
series: []
lastmod: '2022-10-24T09:08:22-04:00'
featuredVideo: ~
featuredImage: ~
---


Beneficence: Be transparent about limits of data

Our data has been collected by the MLB over a long historical period. Although we will be exclusively using data relevant to the past ten years, we are limited to the reporting of the MLB matching up with weather data. Since weather data is specific to location, we are limited to focusing on select teams solely playing at home instead of the MLB as a whole. Since we will be collecting weather data from the city as a whole, it may not be the most accurate representation of the exact weather conditions at the stadium; based on the proximity of the weather station to the stadium itself. Additional factors outside of game data and weather such as random stadium factors will not be a part of our analysis. 

Justice: Return data and research results to community members in a form they can use

Our research results should be useful to MLB teams, or at least the specific teams we focus on, to allow for better anticipatory guidance in the pursuit of winning games. We seek to explore what factors--either internal or external--affect the outcomes of baseball games, which would be useful to know going into a season. Even if we pick to concentrate on one or a few teams/cities, our research methodology should be straightforward and replicable, so any other team could easily attain such results.

Potential abuse or misuse of data:

This data could possibly be abused for personal benefit. However, in this data set and analysis, all teams in the MLB will be represented, not just select favorites of the users. Furthermore, the analyses will be objective to the results found rather than tailored to those select favorites. 

We referenced the following article to better understand data equity and our responsibilities for this project. If you are interested in further research or have additional questions about data equity, we invite you to visit the following site:

Site: https://www.urban.org/research/publication/principles-advancing-equitable-data-practice

pdf: https://friendsnrc.org/wp-content/uploads/2021/05/Principles-for-Advancing-Equitable-Data-Practice.pdf
Discuss how the principles for advancing equitable data practice are relevant to your data. I realize that many of the principles require interaction with communities but think about how the principles could be applied if possible.
For two or three of principles, talk about how they are relevant and what adhering to the practice would entail for your data.
A particularly important principle is transparency. Talk about what might be some limitations of your analysis.
Discuss the potential for abuse or misuse of the data. 