---
title: Interactive Plot, Week of 11/14/22
author: Daniel Sussman
date: '2022-11-14'
slug: []
categories: []
tags: []
description: ~
toc: yes
authors: []
series: []
lastmod: '2022-11-14T09:43:26-05:00'
featuredVideo: ~
featuredImage: ~
---

Today, we’ll build and deploy a very simple interactive in class and discuss what makes a good interactive.
For this weeks post, describe your thoughts and progress on the interactive for your final project. Think about the principals we talked about from last week the interactive should :

allow the user to both see the big picture trends and to “zoom in” on subsets or individual data points.

be interactive, it should be more than just static plots, allowing the user to provide input to explore the data,

guide the user, providing clear ways to use the interactive and highlighting interesting findings to start a user’s exploration,

if you can, be personal. Not all data will be conducive to this but if you allow a user to see information relevant to them specifically, it can help pull people in.

Discuss your ideas and, if you’ve made progress, provide a link to a draft of the interactive. Note, I’m requiring all groups to use Shiny this semester. The directions on the Big Picture page were not properly updated.

Maybe use shiny to sort by years, and then in leaflet have a popup for winning percentage, and a scroll bar to select for certain winning percentages

```{r, Hannah h}
library(tidyverse)
library(rvest)
library(tibble)
library(readxl)
library(leaflet)
library(dplyr)
library(readr)
library(googlesheets4)



load(here::here("dataset", "baseball.RData"))



load(here::here("dataset", "baseball.RData"))
stadiums <- read_sheet("https://docs.google.com/spreadsheets/d/1p0R5qqR7XjoRG2mR5E1D_trlygHSqMOUdMgMpzq0gjU/htmlview")


AL_east <- c('BAL', 'BOS', 'NYA', 'TBA', 'TOR')
AL_central <- c('MIN', 'CLE', 'CHA', 'DET', 'KCN', 'KCR')
AL_west <- c('ANA', 'HOU', 'SEA', 'OAK', 'TEX' )
NL_east <- c('NYM', 'PHI', 'ATL', 'WAS', 'FLO' )
NL_central<- c('PTL','SLN',  'ATL', 'CHN', 'MIL', 'CIN')

mlbDivision <- function(x){
    
  if(x %in% AL_east){y <- 'AL East'} 
  else if(x %in% AL_central){y <- 'AL Central'} 
  else if(x %in% AL_west){y <- 'AL West'} 
  else if(x %in% NL_east){y <- 'NL East'} 
  else if(x %in% c(NL_central)){y <- 'NL Central'} 
  else { y <- 'NL West'}
  return(y)
}

icons <- makeAwesomeIcon(
    icon = 'circle',
    iconColor = 'black',
    library = 'glyphicon',
    markerColor = ifelse(stadiums$Abbreviation %in% AL_east, 'red',
                  ifelse(stadiums$`Team(s)` %in% AL_central,'blue',
                  ifelse(stadiums$`Team(s)` %in% AL_west, 'orange',
                  ifelse(stadiums$`Team(s)` %in% NL_east,'green',
                  ifelse(stadiums$`Team(s)` %in% NL_central,'darkpurple','black'))))))



mlbColor <- function(x){
    
  if(x == 'AL East'){y <- 'blue'}
  else if(x == 'AL Central'){y <- 'green'}
  else if(x == 'AL West'){y <- 'yellow'}
  else if(x == 'NL East'){y <- 'red'}
  else if(x == 'NL Central'){y <- 'purple'} 
  else {y <- 'black'}
  return(y)
  }


stadiums$Abbreviation[stadiums$Abbreviation == 'CHC'] <- 'CHN'
stadiums$Abbreviation[stadiums$Abbreviation == 'CHW'] <- 'CHA'
stadiums$Abbreviation[stadiums$Abbreviation == 'KCR'] <- 'KCN'
stadiums$Abbreviation[stadiums$Abbreviation == 'LAA'] <- 'ANA'
stadiums$Abbreviation[stadiums$Abbreviation == 'LAD'] <- 'LAN'
stadiums$Abbreviation[stadiums$Abbreviation == 'MIA'] <- 'FLO'
stadiums$Abbreviation[stadiums$Abbreviation == 'NYM'] <- 'NYN'
stadiums$Abbreviation[stadiums$Abbreviation == 'NYY'] <- 'NYA'
stadiums$Abbreviation[stadiums$Abbreviation == 'SDP'] <- 'SDN'
stadiums$Abbreviation[stadiums$Abbreviation == 'SFG'] <- 'SFN'
stadiums$Abbreviation[stadiums$Abbreviation == 'STL'] <- 'SLN'
stadiums$Abbreviation[stadiums$Abbreviation == 'TBR'] <- 'TBA'

MLBstadiums <- stadiums %>% filter(Sport == "MLB") %>% 
  mutate(Division = sapply(X = Abbreviation, FUN = mlbDivision),
           DivisionColor = sapply(X = Division, FUN = mlbColor),
           teamLabs = paste0('Team: ',Abbreviation,'\nField: ',Venue))



baseball_w_stadiums <- merge(baseball, stadiums, by.x=c("h_name"), 
                                                 by.y =("Abbreviation")) 


#leaflet(baseball_w_stadiums) %>% 
  #    setView(lng = -98.5795, lat = 39.8283, zoom = 5) %>% 
  #    addTiles() %>% 
  #    addAwesomeMarkers(~Longitude, ~Latitude, label = ~as.character(h_name)) #%>%
      #addLegend(position = 'bottomleft', opacity = 1,title = 'Divisions')


#save(MLBstadiums, file = "dataset/MLBstadiums.Rdata")


  
makeColorsandNames <- data.frame(divisions = c('AL East','AL Central','AL West','NL East','NL Central','NL West'), division.cent = c('#CC0000','#3399FF','#FFA500','#9ACD32','#483D8B','#000000'))

leaflet(MLBstadiums) %>% 
      setView(lng = -98.5795, lat = 39.8283, zoom = 5) %>% 
      addTiles() %>% 
      addAwesomeMarkers(~Longitude, ~Latitude, icon = icons, label = ~as.character(Venue), popup = ~as.character(Sport)) %>% 
      addLegend(position = 'bottomleft', colors = makeColorsandNames[,2],labels = makeColorsandNames[,1],opacity = 1,title = 'Divisions')

    
```
